### ISSUE TITLE
There is an error when I create an OSS volume using examples from this repo

### ISSUE THREAD

**Issue by jinmiaoluo** [AliyunContainerService/serverless-k8s-examples#16]
Error Information
```
Pod ubuntu-pod requires volume oss which is of an unsupported type
```

deployment content
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image:  registry-vpc.cn-shanghai.aliyuncs.com/jovi/ubuntu:latest
    imagePullPolicy: Always
    command: ["sleep", "1000"]
    volumeMounts:
    - name: oss
      mountPath: "/oss"
  volumes:
  - name: "oss"
    flexVolume:
      driver: "alicloud/oss"
      options:
        bucket: "xxx"
        url: "oss-cn-beijing.aliyuncs.com"
        akId: "xxx"
        akSecret: "xxx"
  restartPolicy: Never
```

PS: my akId and akSecret is created from a sub-account which have OSS full access permission.
