### ISSUE TITLE
安装磁盘控制器yaml文件里的special.keyid和special.keysecret是什么，哪里获取

### ISSUE THREAD

**Issue by einsone** [AliyunContainerService/serverless-k8s-examples#23]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  special.keyid: "xxx"
  special.keysecret: "xxx"
```
keyid和keysecret哪里获取，NAS控制台没有
