### ISSUE TITLE
HTTPS  SLB 400 Bad Request

### ISSUE THREAD

**Issue by slzzz** [AliyunContainerService/serverless-k8s-examples#32]
hello，我在试图通过slb https协议访问k8s 内部http应用是遇到400 Bad Request
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: test
    servicePort: 80
  rules:
  - host: x.x.x.x
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: test
```

kube-system   nginx-ingress-lb   LoadBalancer   192.168.173.129   x.x.x.x 80:30369/TCP,443:31110/TCP   2d20h

当将ssl放到ingress，并且修改slb为tcp是工作正常

问题： 已经在slb配置证书，为啥无法工作？
